import React, { useState } from "react";
import {
    Document,
    Page,
    Text,
    View,
    PDFViewer,
    PDFDownloadLink,
} from '@react-pdf/renderer';

import { reportStyles } from '@/styles/pdfReportStyles';
import {
    formatDate,
    formatTime,
    generateFileName,
    formatItemSupplierStatus,
    getItemSupplierStatusStyle
} from '@/utils/pdfReportUtils';
import "@/styles/pdfModal.css";

// Interface definitions
interface ItemItem {
    id: number;
    itemName: string;
    itemUnitMeasure: string;
    itemCategory: string;
    linkedSupplier: number;
    itemStatus: string;
}

interface ItemReportPDFProps {
    isOpen: boolean;
    onClose: () => void;
    itemData: ItemItem[];
    reportTitle?: string;
}

// PDF Document Component
const ItemReportDocument: React.FC<{
    itemData: ItemItem[],
    reportTitle?: string
}> = ({ itemData, reportTitle = "Item Management Report" }) => {

    const today = new Date();

    // Calculate summary statistics
    const totalItem = itemData.length;
    const activeItem = itemData.filter(item => item.itemStatus === 'ACTIVE' || item.itemStatus === 'active').length;
    const inactiveItem = itemData.filter(item => item.itemStatus === 'INACTIVE' || item.itemStatus === 'inactive').length;

    return (
        <Document>
            <Page size="LETTER" style={reportStyles.page}>
                {/* Header Section */}
                <View style={reportStyles.header}>
                    <Text style={reportStyles.companyName}>Agila Bus Transport Corp.</Text>
                    <Text style={reportStyles.title}>{reportTitle}</Text>
                    <Text style={reportStyles.dateTime}>
                        Generated on {formatDate(today)} at {formatTime(today)}
                    </Text>
                    <Text style={reportStyles.reportInfo}>
                        Total Item: {totalItem}
                    </Text>
                </View>

                {/* Divider */}
                <View style={reportStyles.divider} />

                {/* Summary Section */}
                <View style={reportStyles.summarySection}>
                    <View style={reportStyles.summaryItem}>
                        <Text style={reportStyles.summaryNumber}>{activeItem}</Text>
                        <Text style={reportStyles.summaryLabel}>Active Item</Text>
                    </View>
                    <View style={reportStyles.summaryItem}>
                        <Text style={reportStyles.summaryNumber}>{inactiveItem}</Text>
                        <Text style={reportStyles.summaryLabel}>Inactive Item</Text>
                    </View>
                </View>

                {/* Table */}
                <View style={reportStyles.table}>
                    {/* Table Header */}
                    <View style={reportStyles.tableHeader}>
                        <Text style={reportStyles.columnMedium}>Item Name</Text>
                        <Text style={reportStyles.columnMedium}>Unit Measure</Text>
                        <Text style={reportStyles.columnMedium}>Category</Text>
                        <Text style={reportStyles.columnMedium}>Linked Supplier</Text>
                        <Text style={reportStyles.columnMedium}>Status</Text>
                    </View>

                    {/* Table Rows */}
                    {itemData.map((item, index) => (
                        <View
                            key={item.id}
                            style={[
                                reportStyles.tableRow,
                                index % 2 === 1 ? reportStyles.alternateRow : {}
                            ]}
                        >
                            <Text style={reportStyles.columnMedium}>
                                {item.itemName}
                            </Text>
                            <Text style={reportStyles.columnMedium}>
                                {item.itemUnitMeasure}
                            </Text>
                            <Text style={reportStyles.columnMedium}>
                                {item.itemCategory}
                            </Text>
                            <Text style={reportStyles.columnMedium}>
                                {item.linkedSupplier}
                            </Text>
                            <View style={reportStyles.statusContainer}>
                                <Text style={getItemSupplierStatusStyle(item.itemStatus)}>
                                    {formatItemSupplierStatus(item.itemStatus)}
                                </Text>
                            </View>
                        </View>
                    ))}
                </View>

                {/* Footer */}
                <Text style={reportStyles.footer}>
                    This report was electronically generated by the Agila Bus Transport Corp. - Inventory Management System
                </Text>

                {/* Page Number */}
                <Text style={reportStyles.pageNumber} render={({ pageNumber, totalPages }) => (
                    `Page ${pageNumber} of ${totalPages}`
                )} fixed />
            </Page>
        </Document>
    );
};

// PDF Preview Modal Component
export const ItemReportPreviewModal: React.FC<ItemReportPDFProps> = ({
    isOpen,
    onClose,
    itemData,
    reportTitle
}) => {
    if (!isOpen) return null;

    return (
        <div className="pdf-modal-overlay">
            <div className="pdf-modal">
                <div className="pdf-modal-content">
                    <div className="pdf-container">
                        <PDFViewer width="100%" height="100%">
                            <ItemReportDocument
                                itemData={itemData}
                                reportTitle={reportTitle}
                            />
                        </PDFViewer>
                    </div>

                    <div className="pdf-modal-actions">
                        <button className="close-btn" onClick={onClose}>Close</button>
                        <PDFDownloadLink
                            document={
                                <ItemReportDocument
                                    itemData={itemData}
                                    reportTitle={reportTitle}
                                />
                            }
                            fileName={generateFileName('Item')}
                            className="download-btn"
                        >
                            {({ blob, url, loading, error }) =>
                                loading ?
                                    'Preparing document...' :
                                    <><i className="ri-file-download-line" /> Download PDF</>
                            }
                        </PDFDownloadLink>
                    </div>
                </div>
            </div>
        </div>
    );
};

// Custom hook for item report PDF functionality
export const useItemReportPDF = (itemData: ItemItem[]) => {
    const [showReportPreview, setShowReportPreview] = useState(false);
    const [reportTitle, setReportTitle] = useState("Item Management Report");

    const handlePreviewReport = () => {
        setShowReportPreview(true);
    };

    const handleCloseReportPreview = () => {
        setShowReportPreview(false);
    };

    return {
        showReportPreview,
        handlePreviewReport,
        handleCloseReportPreview,
        reportTitle,
        setReportTitle
    };
};