import React, { useState } from "react";
import {
    Document,
    Page,
    Text,
    View,
    PDFViewer,
    PDFDownloadLink,
} from '@react-pdf/renderer';

import { reportStyles } from '@/styles/pdfReportStyles';
import {
    formatDate,
    formatTime,
    generateFileName,
} from '@/utils/pdfReportUtils';
import "@/styles/pdfModal.css";

// Interface definitions
interface StockDisposalItem {
    id: number;
    itemName: string;
    category: string;
    sku: string;
    disposalMethod: string;
    disposalDate: string;
}

interface StockDisposalReportPDFProps {
    isOpen: boolean;
    onClose: () => void;
    stockDisposalData: StockDisposalItem[];
    reportTitle?: string;
}

// PDF Document Component
const StockDisposalReportDocument: React.FC<{
    stockDisposalData: StockDisposalItem[],
    reportTitle?: string
}> = ({ stockDisposalData, reportTitle = "Stock Disposal Report" }) => {

    const today = new Date();

    // Calculate summary statistics
    const totalStockDisposal = stockDisposalData.length;

    return (
        <Document>
            <Page size="LETTER" style={reportStyles.page}>
                {/* Header Section */}
                <View style={reportStyles.header}>
                    <Text style={reportStyles.companyName}>Agila Bus Transport Corp.</Text>
                    <Text style={reportStyles.title}>{reportTitle}</Text>
                    <Text style={reportStyles.dateTime}>
                        Generated on {formatDate(today)} at {formatTime(today)}
                    </Text>
                    <Text style={reportStyles.reportInfo}>
                        Total Stock Disposal: {totalStockDisposal}
                    </Text>
                </View>

                {/* Divider */}
                <View style={reportStyles.divider} />

                {/* Table */}
                <View style={reportStyles.table}>
                    {/* Table Header */}
                    <View style={reportStyles.tableHeader}>
                        <Text style={reportStyles.columnMedium}>SKU</Text>
                        <Text style={reportStyles.columnMedium}>Item Name</Text>
                        <Text style={reportStyles.columnMedium}>Category</Text>
                        <Text style={reportStyles.columnMedium}>Disposal Method</Text>
                        <Text style={reportStyles.columnMedium}>Disposal Date</Text>
                    </View>

                    {/* Table Rows */}
                    {stockDisposalData.map((item, index) => (
                        <View
                            key={item.id}
                            style={[
                                reportStyles.tableRow,
                                index % 2 === 1 ? reportStyles.alternateRow : {}
                            ]}
                        >
                            <Text style={reportStyles.columnMedium}>
                                {item.sku}
                            </Text>
                            <Text style={reportStyles.columnMedium}>
                                {item.itemName}
                            </Text>
                            <Text style={reportStyles.columnMedium}>
                                {item.category}
                            </Text>
                            <Text style={reportStyles.columnMedium}>
                                {item.disposalMethod}
                            </Text>
                            <Text style={reportStyles.columnMedium}>
                                {item.disposalDate}
                            </Text>
                        </View>
                    ))}
                </View>

                {/* Footer */}
                <Text style={reportStyles.footer}>
                    This report was electronically generated by the Agila Bus Transport Corp. - Inventory Management System
                </Text>

                {/* Page Number */}
                <Text style={reportStyles.pageNumber} render={({ pageNumber, totalPages }) => (
                    `Page ${pageNumber} of ${totalPages}`
                )} fixed />
            </Page>
        </Document>
    );
};

// PDF Preview Modal Component
export const StockDisposalReportPreviewModal: React.FC<StockDisposalReportPDFProps> = ({
    isOpen,
    onClose,
    stockDisposalData,
    reportTitle
}) => {
    if (!isOpen) return null;

    return (
        <div className="pdf-modal-overlay">
            <div className="pdf-modal">
                <div className="pdf-modal-content">
                    <div className="pdf-container">
                        <PDFViewer width="100%" height="100%">
                            <StockDisposalReportDocument
                                stockDisposalData={stockDisposalData}
                                reportTitle={reportTitle}
                            />
                        </PDFViewer>
                    </div>

                    <div className="pdf-modal-actions">
                        <button className="close-btn" onClick={onClose}>Close</button>
                        <PDFDownloadLink
                            document={
                                <StockDisposalReportDocument
                                    stockDisposalData={stockDisposalData}
                                    reportTitle={reportTitle}
                                />
                            }
                            fileName={generateFileName('Stock-Disposal')}
                            className="download-btn"
                        >
                            {({ blob, url, loading, error }) =>
                                loading ?
                                    'Preparing document...' :
                                    <><i className="ri-file-download-line" /> Download PDF</>
                            }
                        </PDFDownloadLink>
                    </div>
                </div>
            </div>
        </div>
    );
};

// Custom hook for stock disposal report PDF functionality
export const useStockDisposalReportPDF = (stockDisposalData: StockDisposalItem[]) => {
    const [showReportPreview, setShowReportPreview] = useState(false);
    const [reportTitle, setReportTitle] = useState("Stock Disposal Report");

    const handlePreviewReport = () => {
        setShowReportPreview(true);
    };

    const handleCloseReportPreview = () => {
        setShowReportPreview(false);
    };

    return {
        showReportPreview,
        handlePreviewReport,
        handleCloseReportPreview,
        reportTitle,
        setReportTitle
    };
};