import React, { useState } from "react";
import {
    Document,
    Page,
    Text,
    View,
    PDFViewer,
    PDFDownloadLink,
} from '@react-pdf/renderer';

import { reportStyles } from '@/styles/pdfReportStyles';
import {
    formatDate,
    formatTime,
    generateFileName,
} from '@/utils/pdfReportUtils';
import "@/styles/pdfModal.css";

// Interface definitions
interface BusDisposalItem {
    id: number;
    bodyNumber: string;
    bodyBuilder: string;
    busType: string;
    disposalMethod: string;
    disposalDate: string;
}

interface BusDisposalReportPDFProps {
    isOpen: boolean;
    onClose: () => void;
    busDisposalData: BusDisposalItem[];
    reportTitle?: string;
}

// PDF Document Component
const BusDisposalReportDocument: React.FC<{
    busDisposalData: BusDisposalItem[],
    reportTitle?: string
}> = ({ busDisposalData, reportTitle = "Bus Disposal Report" }) => {

    const today = new Date();

    // Calculate summary statistics
    const totalBusDisposal = busDisposalData.length;

    return (
        <Document>
            <Page size="LETTER" style={reportStyles.page}>
                {/* Header Section */}
                <View style={reportStyles.header}>
                    <Text style={reportStyles.companyName}>Agila Bus Transport Corp.</Text>
                    <Text style={reportStyles.title}>{reportTitle}</Text>
                    <Text style={reportStyles.dateTime}>
                        Generated on {formatDate(today)} at {formatTime(today)}
                    </Text>
                    <Text style={reportStyles.reportInfo}>
                        Total Bus Disposal: {totalBusDisposal}
                    </Text>
                </View>

                {/* Divider */}
                <View style={reportStyles.divider} />

                {/* Table */}
                <View style={reportStyles.table}>
                    {/* Table Header */}
                    <View style={reportStyles.tableHeader}>
                        <Text style={reportStyles.columnSmall}>Body Number</Text>
                        <Text style={reportStyles.columnSmall}>Body Builder</Text>
                        <Text style={reportStyles.columnMedium}>Bus Type</Text>
                        <Text style={reportStyles.columnMedium}>Disposal Method</Text>
                        <Text style={reportStyles.columnMedium}>Disposal Date</Text>
                    </View>

                    {/* Table Rows */}
                    {busDisposalData.map((item, index) => (
                        <View
                            key={item.id}
                            style={[
                                reportStyles.tableRow,
                                index % 2 === 1 ? reportStyles.alternateRow : {}
                            ]}
                        >
                            <Text style={reportStyles.columnSmall}>
                                {item.bodyNumber}
                            </Text>
                            <Text style={reportStyles.columnSmall}>
                                {item.bodyBuilder}
                            </Text>
                            <Text style={reportStyles.columnMedium}>
                                {item.busType}
                            </Text>
                            <Text style={reportStyles.columnMedium}>
                                {item.disposalMethod}
                            </Text>
                            <Text style={reportStyles.columnMedium}>
                                {item.disposalDate}
                            </Text>
                        </View>
                    ))}
                </View>

                {/* Footer */}
                <Text style={reportStyles.footer}>
                    This report was electronically generated by the Agila Bus Transport Corp. - Inventory Management System
                </Text>

                {/* Page Number */}
                <Text style={reportStyles.pageNumber} render={({ pageNumber, totalPages }) => (
                    `Page ${pageNumber} of ${totalPages}`
                )} fixed />
            </Page>
        </Document>
    );
};

// PDF Preview Modal Component
export const BusDisposalReportPreviewModal: React.FC<BusDisposalReportPDFProps> = ({
    isOpen,
    onClose,
    busDisposalData,
    reportTitle
}) => {
    if (!isOpen) return null;

    return (
        <div className="pdf-modal-overlay">
            <div className="pdf-modal">
                <div className="pdf-modal-content">
                    <div className="pdf-container">
                        <PDFViewer width="100%" height="100%">
                            <BusDisposalReportDocument
                                busDisposalData={busDisposalData}
                                reportTitle={reportTitle}
                            />
                        </PDFViewer>
                    </div>

                    <div className="pdf-modal-actions">
                        <button className="close-btn" onClick={onClose}>Close</button>
                        <PDFDownloadLink
                            document={
                                <BusDisposalReportDocument
                                    busDisposalData={busDisposalData}
                                    reportTitle={reportTitle}
                                />
                            }
                            fileName={generateFileName('Bus-Disposal')}
                            className="download-btn"
                        >
                            {({ blob, url, loading, error }) =>
                                loading ?
                                    'Preparing document...' :
                                    <><i className="ri-file-download-line" /> Download PDF</>
                            }
                        </PDFDownloadLink>
                    </div>
                </div>
            </div>
        </div>
    );
};

// Custom hook for bus disposal report PDF functionality
export const useBusDisposalReportPDF = (busDisposalData: BusDisposalItem[]) => {
    const [showReportPreview, setShowReportPreview] = useState(false);
    const [reportTitle, setReportTitle] = useState("Bus Disposal Report");

    const handlePreviewReport = () => {
        setShowReportPreview(true);
    };

    const handleCloseReportPreview = () => {
        setShowReportPreview(false);
    };

    return {
        showReportPreview,
        handlePreviewReport,
        handleCloseReportPreview,
        reportTitle,
        setReportTitle
    };
};