// src/components/reports/order/OrderReportPDF.tsx
import React, { useState } from "react";
import {
    Document,
    Page,
    Text,
    View,
    PDFViewer,
    PDFDownloadLink,
} from '@react-pdf/renderer';

import { reportStyles } from '@/styles/pdfReportStyles';
import {
    formatDate,
    formatTime,
    generateFileName,
    formatOrderStatus,
    getOrderStatusStyle
} from '@/utils/pdfReportUtils';
import "@/styles/pdfModal.css";

// Interface definitions
interface OrderItem {
    id: number;
    itemName: string;
    ordQuantity: number;
    ordReqDate: string;
    ordStatus: string;
}

interface OrderReportPDFProps {
    isOpen: boolean;
    onClose: () => void;
    orderData: OrderItem[];
    reportTitle?: string;
}

// PDF Document Component
const OrderReportDocument: React.FC<{
    orderData: OrderItem[],
    reportTitle?: string
}> = ({ orderData, reportTitle = "Order Management Report" }) => {
    const today = new Date();

    // Calculate summary statistics
    const totalOrder = orderData.length;
    const approvedOrders = orderData.filter(item => item.ordStatus === 'approved').length;
    const pendingOrders = orderData.filter(item => item.ordStatus === 'pending').length;
    const completedOrders = orderData.filter(item => item.ordStatus === 'completed').length;

    return (
        <Document>
            <Page size="LETTER" style={reportStyles.page}>
                {/* Header Section */}
                <View style={reportStyles.header}>
                    <Text style={reportStyles.companyName}>Agila Bus Transport Corp.</Text>
                    <Text style={reportStyles.title}>{reportTitle}</Text>
                    <Text style={reportStyles.dateTime}>
                        Generated on {formatDate(today)} at {formatTime(today)}
                    </Text>
                    <Text style={reportStyles.reportInfo}>
                        Total Order Requests: {totalOrder}
                    </Text>
                </View>

                {/* Divider */}
                <View style={reportStyles.divider} />

                {/* Summary Section */}
                <View style={reportStyles.summarySection}>
                    <View style={reportStyles.summaryItem}>
                        <Text style={reportStyles.summaryNumber}>{approvedOrders}</Text>
                        <Text style={reportStyles.summaryLabel}>Approved Orders</Text>
                    </View>
                    <View style={reportStyles.summaryItem}>
                        <Text style={reportStyles.summaryNumber}>{pendingOrders}</Text>
                        <Text style={reportStyles.summaryLabel}>Pending Orders</Text>
                    </View>
                    <View style={reportStyles.summaryItem}>
                        <Text style={reportStyles.summaryNumber}>{completedOrders}</Text>
                        <Text style={reportStyles.summaryLabel}>Completed Orders</Text>
                    </View>
                </View>

                {/* Table */}
                <View style={reportStyles.table}>
                    {/* Table Header */}
                    <View style={reportStyles.tableHeader}>
                        <Text style={reportStyles.columnLarge}>Item Name</Text>
                        <Text style={reportStyles.columnMedium}>Requested Quantity</Text>
                        <Text style={reportStyles.columnMedium}>Request Date</Text>
                        <Text style={reportStyles.columnMedium}>Status</Text>
                    </View>

                    {/* Table Rows */}
                    {orderData.map((item, index) => (
                        <View
                            key={item.id}
                            style={[
                                reportStyles.tableRow,
                                index % 2 === 1 ? reportStyles.alternateRow : {}
                            ]}
                        >
                            <Text style={reportStyles.columnLarge}>
                                {item.itemName}
                            </Text>
                            <Text style={reportStyles.columnMedium}>
                                {item.ordQuantity}
                            </Text>
                            <Text style={reportStyles.columnMedium}>
                                {item.ordReqDate}
                            </Text>
                            <View style={reportStyles.statusContainer}>
                                <Text style={getOrderStatusStyle(item.ordStatus)}>
                                    {formatOrderStatus(item.ordStatus)}
                                </Text>
                            </View>
                        </View>
                    ))}
                </View>

                {/* Footer */}
                <Text style={reportStyles.footer}>
                    This report was electronically generated by the Agila Bus Transport Corp. - Inventory Management System
                </Text>

                {/* Page Number */}
                <Text style={reportStyles.pageNumber} render={({ pageNumber, totalPages }) => (
                    `Page ${pageNumber} of ${totalPages}`
                )} fixed />
            </Page>
        </Document>
    );
};

// PDF Preview Modal Component
export const OrderReportPreviewModal: React.FC<OrderReportPDFProps> = ({
    isOpen,
    onClose,
    orderData,
    reportTitle
}) => {
    if (!isOpen) return null;

    return (
        <div className="pdf-modal-overlay">
            <div className="pdf-modal">
                <div className="pdf-modal-content">
                    <div className="pdf-container">
                        <PDFViewer width="100%" height="100%">
                            <OrderReportDocument
                                orderData={orderData}
                                reportTitle={reportTitle}
                            />
                        </PDFViewer>
                    </div>

                    <div className="pdf-modal-actions">
                        <button className="close-btn" onClick={onClose}>Close</button>
                        <PDFDownloadLink
                            document={
                                <OrderReportDocument
                                    orderData={orderData}
                                    reportTitle={reportTitle}
                                />
                            }
                            fileName={generateFileName('order')}
                            className="download-btn"
                        >
                            {({ blob, url, loading, error }) =>
                                loading ?
                                    'Preparing document...' :
                                    <><i className="ri-file-download-line" /> Download PDF</>
                            }
                        </PDFDownloadLink>
                    </div>
                </div>
            </div>
        </div>
    );
};

// Custom hook for order report PDF functionality
export const useOrderReportPDF = (orderData: OrderItem[]) => {
    const [showReportPreview, setShowReportPreview] = useState(false);
    const [reportTitle, setReportTitle] = useState("Order Management Report");

    const handlePreviewReport = () => {
        setShowReportPreview(true);
    };

    const handleCloseReportPreview = () => {
        setShowReportPreview(false);
    };

    return {
        showReportPreview,
        handlePreviewReport,
        handleCloseReportPreview,
        reportTitle,
        setReportTitle
    };
};